// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/users": {
            "get": {
                "description": "Get a list of all users in the database.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Get all users",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.SwaggerUser"
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "models.SwaggerUser": {
            "type": "object",
            "properties": {
                "actived": {
                    "type": "string"
                },
                "balance": {
                    "type": "number"
                },
                "bankname": {
                    "type": "string"
                },
                "banknumber": {
                    "type": "string"
                },
                "beforebalance": {
                    "type": "number"
                },
                "betamount": {
                    "type": "number"
                },
                "createdAt": {
                    "type": "string"
                },
                "credit": {
                    "type": "number"
                },
                "deletionAt": {
                    "type": "string"
                },
                "deposit": {
                    "type": "number"
                },
                "firstname": {
                    "type": "string"
                },
                "fullname": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "lastname": {
                    "type": "string"
                },
                "lose": {
                    "type": "number"
                },
                "otpAuthUrl": {
                    "type": "string"
                },
                "partnersKey": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                },
                "preferredname": {
                    "type": "string"
                },
                "prefix": {
                    "type": "string"
                },
                "proID": {
                    "type": "string"
                },
                "proStatus": {
                    "type": "string"
                },
                "providerPassword": {
                    "type": "string"
                },
                "role": {
                    "type": "string"
                },
                "salt": {
                    "type": "string"
                },
                "secret": {
                    "type": "string"
                },
                "status": {
                    "type": "integer"
                },
                "tempSecret": {
                    "type": "string"
                },
                "token": {
                    "type": "string"
                },
                "turnover": {
                    "type": "number"
                },
                "updatedAt": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                },
                "walletid": {
                    "type": "integer"
                },
                "win": {
                    "type": "number"
                },
                "withdraw": {
                    "type": "number"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:3003",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "Swagger Example API",
	Description:      "This is a sample server for Swagger with GORM and MySQL in Go.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
